<?php

// File generated from our OpenAPI spec

namespace Paayes\Util;

class ObjectTypes
{
    /**
     * @var array Mapping from object types to resource classes
     */
    const mapping = [
        \Paayes\Account::OBJECT_NAME => \Paayes\Account::class,
        \Paayes\AccountLink::OBJECT_NAME => \Paayes\AccountLink::class,
        \Paayes\AlipayAccount::OBJECT_NAME => \Paayes\AlipayAccount::class,
        \Paayes\ApplePayDomain::OBJECT_NAME => \Paayes\ApplePayDomain::class,
        \Paayes\ApplicationFee::OBJECT_NAME => \Paayes\ApplicationFee::class,
        \Paayes\ApplicationFeeRefund::OBJECT_NAME => \Paayes\ApplicationFeeRefund::class,
        \Paayes\Balance::OBJECT_NAME => \Paayes\Balance::class,
        \Paayes\BalanceTransaction::OBJECT_NAME => \Paayes\BalanceTransaction::class,
        \Paayes\BankAccount::OBJECT_NAME => \Paayes\BankAccount::class,
        \Paayes\BillingPortal\Configuration::OBJECT_NAME => \Paayes\BillingPortal\Configuration::class,
        \Paayes\BillingPortal\Session::OBJECT_NAME => \Paayes\BillingPortal\Session::class,
        \Paayes\BitcoinReceiver::OBJECT_NAME => \Paayes\BitcoinReceiver::class,
        \Paayes\BitcoinTransaction::OBJECT_NAME => \Paayes\BitcoinTransaction::class,
        \Paayes\Capability::OBJECT_NAME => \Paayes\Capability::class,
        \Paayes\Card::OBJECT_NAME => \Paayes\Card::class,
        \Paayes\Charge::OBJECT_NAME => \Paayes\Charge::class,
        \Paayes\Checkout\Session::OBJECT_NAME => \Paayes\Checkout\Session::class,
        \Paayes\Collection::OBJECT_NAME => \Paayes\Collection::class,
        \Paayes\CountrySpec::OBJECT_NAME => \Paayes\CountrySpec::class,
        \Paayes\Coupon::OBJECT_NAME => \Paayes\Coupon::class,
        \Paayes\CreditNote::OBJECT_NAME => \Paayes\CreditNote::class,
        \Paayes\CreditNoteLineItem::OBJECT_NAME => \Paayes\CreditNoteLineItem::class,
        \Paayes\Customer::OBJECT_NAME => \Paayes\Customer::class,
        \Paayes\CustomerBalanceTransaction::OBJECT_NAME => \Paayes\CustomerBalanceTransaction::class,
        \Paayes\Discount::OBJECT_NAME => \Paayes\Discount::class,
        \Paayes\Dispute::OBJECT_NAME => \Paayes\Dispute::class,
        \Paayes\EphemeralKey::OBJECT_NAME => \Paayes\EphemeralKey::class,
        \Paayes\Event::OBJECT_NAME => \Paayes\Event::class,
        \Paayes\ExchangeRate::OBJECT_NAME => \Paayes\ExchangeRate::class,
        \Paayes\File::OBJECT_NAME => \Paayes\File::class,
        \Paayes\File::OBJECT_NAME_ALT => \Paayes\File::class,
        \Paayes\FileLink::OBJECT_NAME => \Paayes\FileLink::class,
        \Paayes\Identity\VerificationReport::OBJECT_NAME => \Paayes\Identity\VerificationReport::class,
        \Paayes\Identity\VerificationSession::OBJECT_NAME => \Paayes\Identity\VerificationSession::class,
        \Paayes\Invoice::OBJECT_NAME => \Paayes\Invoice::class,
        \Paayes\InvoiceItem::OBJECT_NAME => \Paayes\InvoiceItem::class,
        \Paayes\InvoiceLineItem::OBJECT_NAME => \Paayes\InvoiceLineItem::class,
        \Paayes\Issuing\Authorization::OBJECT_NAME => \Paayes\Issuing\Authorization::class,
        \Paayes\Issuing\Card::OBJECT_NAME => \Paayes\Issuing\Card::class,
        \Paayes\Issuing\CardDetails::OBJECT_NAME => \Paayes\Issuing\CardDetails::class,
        \Paayes\Issuing\Cardholder::OBJECT_NAME => \Paayes\Issuing\Cardholder::class,
        \Paayes\Issuing\Dispute::OBJECT_NAME => \Paayes\Issuing\Dispute::class,
        \Paayes\Issuing\Transaction::OBJECT_NAME => \Paayes\Issuing\Transaction::class,
        \Paayes\LineItem::OBJECT_NAME => \Paayes\LineItem::class,
        \Paayes\LoginLink::OBJECT_NAME => \Paayes\LoginLink::class,
        \Paayes\Mandate::OBJECT_NAME => \Paayes\Mandate::class,
        \Paayes\Order::OBJECT_NAME => \Paayes\Order::class,
        \Paayes\OrderItem::OBJECT_NAME => \Paayes\OrderItem::class,
        \Paayes\OrderReturn::OBJECT_NAME => \Paayes\OrderReturn::class,
        \Paayes\PaymentIntent::OBJECT_NAME => \Paayes\PaymentIntent::class,
        \Paayes\PaymentMethod::OBJECT_NAME => \Paayes\PaymentMethod::class,
        \Paayes\Payout::OBJECT_NAME => \Paayes\Payout::class,
        \Paayes\Person::OBJECT_NAME => \Paayes\Person::class,
        \Paayes\Plan::OBJECT_NAME => \Paayes\Plan::class,
        \Paayes\Price::OBJECT_NAME => \Paayes\Price::class,
        \Paayes\Product::OBJECT_NAME => \Paayes\Product::class,
        \Paayes\PromotionCode::OBJECT_NAME => \Paayes\PromotionCode::class,
        \Paayes\Quote::OBJECT_NAME => \Paayes\Quote::class,
        \Paayes\Radar\EarlyFraudWarning::OBJECT_NAME => \Paayes\Radar\EarlyFraudWarning::class,
        \Paayes\Radar\ValueList::OBJECT_NAME => \Paayes\Radar\ValueList::class,
        \Paayes\Radar\ValueListItem::OBJECT_NAME => \Paayes\Radar\ValueListItem::class,
        \Paayes\Recipient::OBJECT_NAME => \Paayes\Recipient::class,
        \Paayes\RecipientTransfer::OBJECT_NAME => \Paayes\RecipientTransfer::class,
        \Paayes\Refund::OBJECT_NAME => \Paayes\Refund::class,
        \Paayes\Reporting\ReportRun::OBJECT_NAME => \Paayes\Reporting\ReportRun::class,
        \Paayes\Reporting\ReportType::OBJECT_NAME => \Paayes\Reporting\ReportType::class,
        \Paayes\Review::OBJECT_NAME => \Paayes\Review::class,
        \Paayes\SetupAttempt::OBJECT_NAME => \Paayes\SetupAttempt::class,
        \Paayes\SetupIntent::OBJECT_NAME => \Paayes\SetupIntent::class,
        \Paayes\Sigma\ScheduledQueryRun::OBJECT_NAME => \Paayes\Sigma\ScheduledQueryRun::class,
        \Paayes\SKU::OBJECT_NAME => \Paayes\SKU::class,
        \Paayes\Source::OBJECT_NAME => \Paayes\Source::class,
        \Paayes\SourceTransaction::OBJECT_NAME => \Paayes\SourceTransaction::class,
        \Paayes\Subscription::OBJECT_NAME => \Paayes\Subscription::class,
        \Paayes\SubscriptionItem::OBJECT_NAME => \Paayes\SubscriptionItem::class,
        \Paayes\SubscriptionSchedule::OBJECT_NAME => \Paayes\SubscriptionSchedule::class,
        \Paayes\TaxCode::OBJECT_NAME => \Paayes\TaxCode::class,
        \Paayes\TaxId::OBJECT_NAME => \Paayes\TaxId::class,
        \Paayes\TaxRate::OBJECT_NAME => \Paayes\TaxRate::class,
        \Paayes\Terminal\ConnectionToken::OBJECT_NAME => \Paayes\Terminal\ConnectionToken::class,
        \Paayes\Terminal\Location::OBJECT_NAME => \Paayes\Terminal\Location::class,
        \Paayes\Terminal\Reader::OBJECT_NAME => \Paayes\Terminal\Reader::class,
        \Paayes\ThreeDSecure::OBJECT_NAME => \Paayes\ThreeDSecure::class,
        \Paayes\Token::OBJECT_NAME => \Paayes\Token::class,
        \Paayes\Topup::OBJECT_NAME => \Paayes\Topup::class,
        \Paayes\Transfer::OBJECT_NAME => \Paayes\Transfer::class,
        \Paayes\TransferReversal::OBJECT_NAME => \Paayes\TransferReversal::class,
        \Paayes\UsageRecord::OBJECT_NAME => \Paayes\UsageRecord::class,
        \Paayes\UsageRecordSummary::OBJECT_NAME => \Paayes\UsageRecordSummary::class,
        \Paayes\WebhookEndpoint::OBJECT_NAME => \Paayes\WebhookEndpoint::class,
    ];
}
